remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: GESTIONE INNOVATIVA DELLA SICUREZZA DEI PONTI e RISCHIO STRUTTURALE E DA TRAFFICO VEICOLARE
description: Workshop by MOST SPOKE 7 “CCAM e Smart Infrastructure”
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman